# Generated by Django 5.1.5 on 2025-02-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('priority', models.IntegerField(default=3)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.BigIntegerField()),
                ('time_offset', models.FloatField(default=0.0, help_text='Time offset in seconds')),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_in_tasks', to='Utility.command')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_commands', to='taskmanager.task')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='taskmanager.task')),
            ],
        ),
    ]
