# Generated by Django 5.1.5 on 2025-02-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='duration',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
    ]
