# Generated by Django 5.1.5 on 2025-02-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_remove_timeslot_duration_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcommand',
            name='execution_id',
        ),
    ]
