# Generated by Django 5.1.5 on 2025-02-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_remove_taskcommand_execution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcommand',
            name='execution_time',
            field=models.DateTimeField(blank=True, help_text='Calculated execution time', null=True),
        ),
    ]
