# Generated by Django 5.1.5 on 2025-02-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_task_execution_time_taskcommand_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcommand',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
