# Generated by Django 5.1.5 on 2025-02-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_taskcommand_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_name_optional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
