# Generated by Django 5.1.5 on 2025-02-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatellitePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_id', models.CharField(max_length=100, unique=True)),
                ('satellite_id', models.CharField(max_length=100)),
                ('ground_station_id', models.CharField(max_length=100)),
                ('max_elevation', models.FloatField()),
                ('passage_status', models.CharField(max_length=50)),
                ('keyhole_bypass', models.BooleanField()),
                ('source', models.CharField(max_length=50)),
                ('aos', models.DateTimeField()),
                ('tca', models.DateTimeField()),
                ('los', models.DateTimeField()),
                ('passage_result_id', models.CharField(max_length=50)),
                ('policy_type', models.CharField(max_length=50)),
                ('bandwidth_type', models.CharField(max_length=50)),
            ],
        ),
    ]
