# Generated by Django 5.1.5 on 2025-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateID', models.CharField(max_length=255, unique=True)),
                ('passageID', models.CharField(blank=True, max_length=255, null=True)),
                ('AOS', models.DateTimeField()),
                ('LOS', models.DateTimeField()),
            ],
        ),
    ]
