# Generated by Django 5.1.5 on 2025-02-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('velocity', models.JSONField(default=dict)),
                ('storage', models.JSONField(default=dict)),
                ('power', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
            ],
        ),
    ]
