# Generated by Django 5.1.5 on 2025-02-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_adcsattitudeangle177_adcscontrolmode_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
        migrations.AlterModelTable(
            name='power',
            table='power',
        ),
        migrations.AlterModelTable(
            name='storage',
            table='storage',
        ),
    ]
