# Generated by Django 5.1.5 on 2025-02-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimecommanding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplinkmessage',
            name='command_id',
            field=models.CharField(max_length=50),
        ),
    ]
