# Generated by Django 5.1.5 on 2025-02-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtimecommanding', '0002_alter_uplinkmessage_command_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downlinkmessage',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='uplinkmessage',
            name='topic',
        ),
    ]
