# Generated by Django 5.1.5 on 2025-02-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimecommanding', '0003_remove_downlinkmessage_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downlinkmessage',
            name='command_id',
        ),
        migrations.AlterField(
            model_name='uplinkmessage',
            name='command_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uplinkmessage',
            name='payload',
            field=models.TextField(),
        ),
    ]
