# Generated by Django 5.1.5 on 2025-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimecommanding', '0005_remove_uplinkmessage_command_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downlinkmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
