# Generated by Django 5.1.5 on 2025-02-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utility', '0001_initial'),
        ('taskmanager', '0002_remove_timeslot_duration_task_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_set_id', models.BigIntegerField(db_index=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.BigIntegerField()),
                ('time_tag', models.DateTimeField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utility.command')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
                ('schedule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedulemanager.scheduleset')),
            ],
        ),
    ]
