# Generated by Django 5.1.5 on 2025-02-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemanager', '0001_initial'),
        ('taskmanager', '0003_remove_taskcommand_execution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='execution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='taskmanager.taskcommand'),
        ),
    ]
