# Generated by Django 5.1.5 on 2025-02-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemanager', '0002_alter_schedule_execution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='execution_time',
            field=models.DateTimeField(blank=True, help_text='Execution time fetched from TaskCommand', null=True),
        ),
    ]
