# Generated by Django 5.1.5 on 2025-02-21 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemanager', '0003_schedule_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_tag',
        ),
    ]
