# Generated by Django 5.1.5 on 2025-02-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemanager', '0004_remove_schedule_time_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='command',
        ),
    ]
