# Generated by Django 5.1.5 on 2025-02-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemanager', '0005_remove_schedule_command'),
        ('taskmanager', '0006_remove_task_task_id_task_task_name_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='execution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='taskmanager.taskcommand'),
        ),
    ]
